/*
 * Authorization API
 *
 * Nordea Authorization API v5
 *
 * The version of the OpenAPI document: 5.0
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://openapi-generator.tech
 */

use serde_derive::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Agreement {
    /// Agreement ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Agreement type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub agreement_type: Option<String>,
    /// Customer name
    #[serde(rename = "customer_name", skip_serializing_if = "Option::is_none")]
    pub customer_name: Option<String>,
}

#[allow(dead_code)]
impl Agreement {
    pub fn new() -> Agreement {
        Agreement {
            id: None,
            agreement_type: None,
            customer_name: None,
        }
    }
}
