/*
 * Authorization API
 *
 * Nordea Authorization API v5
 *
 * The version of the OpenAPI document: 5.0
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://openapi-generator.tech
 */
use serde_derive::{Deserialize, Serialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AgreementConflictError {
    #[serde(rename = "agreements", skip_serializing_if = "Option::is_none")]
    pub agreements: Option<Vec<crate::api::personal_authorisation::models::Agreement>>,
}

#[allow(dead_code)]
impl AgreementConflictError {
    pub fn new() -> AgreementConflictError {
        AgreementConflictError { agreements: None }
    }
}
