/*
 * Authorization API
 *
 * Nordea Authorization API v5
 *
 * The version of the OpenAPI document: 5.0
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://openapi-generator.tech
 */
use serde_derive::{Deserialize, Serialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetResponse {
    #[serde(rename = "group_header", skip_serializing_if = "Option::is_none")]
    pub group_header: Option<Box<crate::api::personal_authorisation::models::ResponseHeader>>,
    #[serde(rename = "response", skip_serializing_if = "Option::is_none")]
    pub response: Option<Box<crate::api::personal_authorisation::models::AssetsPayload>>,
}


#[allow(dead_code)]
impl AssetResponse {
    pub fn new() -> AssetResponse {
        AssetResponse {
            group_header: None,
            response: None,
        }
    }
}
