/*
 * Authorization API
 *
 * Nordea Authorization API v5
 *
 * The version of the OpenAPI document: 5.0
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://openapi-generator.tech
 */
use serde_derive::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthorizeSelectedAgreementRequest {
    /// Authorization code of authenticated PSU.
    #[serde(rename = "code")]
    pub code: String,
}

#[allow(dead_code)]
impl AuthorizeSelectedAgreementRequest {
    pub fn new(code: String) -> AuthorizeSelectedAgreementRequest {
        AuthorizeSelectedAgreementRequest { code }
    }
}
