/*
 * Authorization API
 *
 * Nordea Authorization API v5
 *
 * The version of the OpenAPI document: 5.0
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://openapi-generator.tech
 */
use serde_derive::{Deserialize, Serialize};


/// ErrorResponse : Error response
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::api::personal_authorisation::models::ErrorPayload>>,
    #[serde(rename = "group_header", skip_serializing_if = "Option::is_none")]
    pub group_header: Option<Box<crate::api::personal_authorisation::models::ResponseHeader>>,
}

#[allow(dead_code)]
impl ErrorResponse {
    /// Error response
    pub fn new() -> ErrorResponse {
        ErrorResponse {
            error: None,
            group_header: None,
        }
    }
}
