/*
 * Authorization API
 *
 * Nordea Authorization API v5
 *
 * The version of the OpenAPI document: 5.0
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://openapi-generator.tech
 */
use serde_derive::{Deserialize, Serialize};


/// RequestEcho : Original request information
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestEcho {
    /// Original request url
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

#[allow(dead_code)]
impl RequestEcho {
    /// Original request information
    pub fn new() -> RequestEcho {
        RequestEcho { url: None }
    }
}
