/*
 * Authorization API
 *
 * Nordea Authorization API v5
 *
 * The version of the OpenAPI document: 5.0
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://openapi-generator.tech
 */

/// ResponseHeader : External response header
use serde_derive::{Deserialize, Serialize};


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseHeader {
    /// Response creation time
    #[serde(rename = "creation_date_time", skip_serializing_if = "Option::is_none")]
    pub creation_date_time: Option<String>,
    /// HTTP code for response
    #[serde(rename = "http_code", skip_serializing_if = "Option::is_none")]
    pub http_code: Option<i32>,
    /// Original request id for correlation purposes
    #[serde(
        rename = "message_identification",
        skip_serializing_if = "Option::is_none"
    )]
    pub message_identification: Option<String>,
    #[serde(rename = "message_pagination", skip_serializing_if = "Option::is_none")]
    pub message_pagination: Option<Box<crate::api::personal_authorisation::models::Pagination>>,
}

#[allow(dead_code)]
impl ResponseHeader {
    /// External response header
    pub fn new() -> ResponseHeader {
        ResponseHeader {
            creation_date_time: None,
            http_code: None,
            message_identification: None,
            message_pagination: None,
        }
    }
}
