/*
 * Authorization API
 *
 * Nordea Authorization API v5
 *
 * The version of the OpenAPI document: 5.0
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://openapi-generator.tech
 */
use serde_derive::{Deserialize, Serialize};


/// TokenRevocationRequest : The token which should be revoked
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TokenRevocationRequest {
    /// The token which should be revoked
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

#[allow(dead_code)]
impl TokenRevocationRequest {
    /// The token which should be revoked
    pub fn new() -> TokenRevocationRequest {
        TokenRevocationRequest { token: None }
    }
}
