use std::collections::{HashMap, HashSet};
use std::string::ToString;

pub struct Languages {
    languages: Vec<Language>,
    headers: HashMap<String, String>,
    settings: HashMap<String, String>,
    bdd_prefixes: HashSet<String>,
    true_strings: HashSet<String>,
    false_strings: HashSet<String>,
}

impl Languages {
    pub fn new() -> Languages {
        Languages {
            languages: vec![],
            headers: HashMap::new(),
            settings: HashMap::new(),
            bdd_prefixes: HashSet::new(),
            true_strings: HashSet::new(),
            false_strings: HashSet::new(),
        }
    }
    pub fn reset(&mut self) {
        self.languages.clear();
        self.headers.clear();
        self.settings.clear();
        self.bdd_prefixes.clear();
        self.true_strings.clear();
        self.false_strings.clear();
    }

    fn add_language(&mut self, lang: Language) {
        if self.languages.contains(&lang){
            return;
        }
        for (n, value) in lang.get_headers() {
            let _ = &self.headers.insert(n.to_string().to_uppercase(),
                                         value.unwrap_or("".to_string()).to_string());
        }
        for (n, value) in lang.get_settings() {
            let _ = &self.settings.insert(n.to_string().to_uppercase(),
                                          value.unwrap_or(String::default()).to_string());
        }
        for n in lang.get_prefixes() {
            let _ = &self.bdd_prefixes.insert(n.to_string().to_uppercase());
        }
        for n in lang.get_true_strings() {
            let _ = &self.true_strings.insert(n.to_string().to_uppercase());
        }
        for n in lang.get_false_strings() {
            let _ = &self.false_strings.insert(n.to_string().to_uppercase());
        }
        self.languages.push(lang);
    }

    fn resolve_languages(&self, languages: Languages, add_english: bool) -> Languages {
        let mut languages = languages;
        if  add_english {
            if !languages.languages.contains(&EN) {
                languages.languages.push(EN);
            }
        }
        languages
    }

    fn get_available_languages(&self) -> HashMap<String, Language> {
        let mut available: HashMap<String, Language> = HashMap::new();
        available.insert("English".to_string(), EN);
        available.insert("Czech".to_string(), CS);
        available.insert("Dutch".to_string(), NL);
        available.insert("Bosnian".to_string(), BS);
        available.insert("Finnish".to_string(), FI);
        available.insert("French".to_string(), FR);
        available.insert("German".to_string(), DE);
        available.insert("Brazilian Portuguese".to_string(), PT_BR);
        available.insert("Portuguese".to_string(), PT);
        available.insert("Thai".to_string(), TH);
        available.insert("Polish".to_string(), PL);
        available.insert("Ukrainian".to_string(), UK);
        available.insert("Spanish".to_string(), ES);
        available.insert("Russian".to_string(), RU);
        available.insert("Chinese Simplified".to_string(), ZH_CN);
        available.insert("Chinese Traditional".to_string(), ZH_TW);
        available.insert("Turkish".to_string(), TR);
        available.insert("Swedish".to_string(), SV);
        available.insert("Bulgarian".to_string(), BG);
        available.insert("Romanian".to_string(), RO);
        available.insert("Italian".to_string(), IT);
        available.insert("Hindi".to_string(), HI);
        available.insert("Vietnamese".to_string(), VI);
        available.insert("Japanese".to_string(), JA);
        available
    }
}

pub struct Language {
    settings_header: Option<&'static str>,
    variables_header: Option<&'static str>,
    test_cases_header: Option<&'static str>,
    tasks_header: Option<&'static str>,
    keywords_header: Option<&'static str>,
    comments_header: Option<&'static str>,
    library_setting: Option<&'static str>,
    resource_setting: Option<&'static str>,
    variables_setting: Option<&'static str>,
    name_setting: Option<&'static str>,
    documentation_setting: Option<&'static str>,
    metadata_setting: Option<&'static str>,
    suite_setup_setting: Option<&'static str>,
    suite_teardown_setting: Option<&'static str>,
    test_setup_setting: Option<&'static str>,
    task_setup_setting: Option<&'static str>,
    test_teardown_setting: Option<&'static str>,
    task_teardown_setting: Option<&'static str>,
    test_template_setting: Option<&'static str>,
    task_template_setting: Option<&'static str>,
    test_timeout_setting: Option<&'static str>,
    task_timeout_setting: Option<&'static str>,
    test_tags_setting: Option<&'static str>,
    task_tags_setting: Option<&'static str>,
    keyword_tags_setting: Option<&'static str>,
    tags_setting: Option<&'static str>,
    setup_setting: Option<&'static str>,
    teardown_setting: Option<&'static str>,
    template_setting: Option<&'static str>,
    timeout_setting: Option<&'static str>,
    arguments_setting: Option<&'static str>,
    given_prefixes: &'static [&'static str],
    when_prefixes: &'static [&'static str],
    then_prefixes: &'static [&'static str],
    and_prefixes: &'static [&'static str],
    but_prefixes: &'static [&'static str],
    true_strings: &'static [&'static str],
    false_strings: &'static [&'static str],
}

impl Language {
    pub fn new() -> Self {
        Self {
            settings_header: None,
            variables_header: None,
            test_cases_header: None,
            tasks_header: None,
            keywords_header: None,
            comments_header: None,
            library_setting: None,
            resource_setting: None,
            variables_setting: None,
            name_setting: None,
            documentation_setting: None,
            metadata_setting: None,
            suite_setup_setting: None,
            suite_teardown_setting: None,
            test_setup_setting: None,
            task_setup_setting: None,
            test_teardown_setting: None,
            task_teardown_setting: None,
            test_template_setting: None,
            task_template_setting: None,
            test_timeout_setting: None,
            task_timeout_setting: None,
            test_tags_setting: None,
            task_tags_setting: None,
            keyword_tags_setting: None,
            tags_setting: None,
            setup_setting: None,
            teardown_setting: None,
            template_setting: None,
            timeout_setting: None,
            arguments_setting: None,
            given_prefixes: &[],
            when_prefixes: &[],
            then_prefixes: &[],
            and_prefixes: &[],
            but_prefixes: &[],
            true_strings: &[],
            false_strings: &[],
        }
    }
    pub fn get_headers(&self) -> HashMap<String, Option<String>> {
        let mut headers: HashMap<String, Option<String>> = HashMap::new();
        // you can follow this structure to map other headers as well
        match self.settings_header {
            None => headers.insert("settings_header".to_string(),
                                   EN.settings_header.map(|s| s.to_string())),
            Some(_) => headers.insert("settings_header".to_string(),
                                      self.settings_header.map(|s| s.to_string()))
        };
        match self.variables_header {
            None => headers.insert("variables_header".to_string(), EN.variables_header.map(|s| s.to_string())),
            Some(_) => headers.insert("variables_header".to_string(), self.variables_header.map(|s| s.to_string()))
        };
        match self.test_cases_header {
            None => headers.insert("test_cases_header".to_string(), EN.test_cases_header.map(|s| s.to_string())),
            Some(_) => headers.insert("test_cases_header".to_string(), self.test_cases_header.map(|s| s.to_string()))
        };
        match self.tasks_header {
            None => headers.insert("tasks_header".to_string(), EN.tasks_header.map(|s| s.to_string())),
            Some(_) => headers.insert("tasks_header".to_string(), self.tasks_header.map(|s| s.to_string())),
        };
        match self.keywords_header {
            None => headers.insert("keywords_header".to_string(), EN.keywords_header.map(|s| s.to_string())),
            Some(_) => headers.insert("keywords_header".to_string(), self.keywords_header.map(|s| s.to_string())),
        };
        match self.comments_header {
            None => headers.insert("comments_header".to_string(), EN.comments_header.map(|s| s.to_string())),
            Some(_) => headers.insert("comments_header".to_string(), self.comments_header.map(|s| s.to_string())),
        };
        headers
    }

    pub fn get_settings(&self) -> HashMap<String, Option<String>> {
        let mut settings: HashMap<String, Option<String>> = HashMap::new();
        match &self.library_setting {
            None => settings.insert("library_setting".to_string(),
                                    EN.library_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("library_setting".to_string(),
                                       self.library_setting.map(|s| s.to_string())),
        };
        match &self.resource_setting {
            None => settings.insert("resource_setting".to_string(),
                                    EN.resource_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("resource_setting".to_string(),
                                       self.resource_setting.map(|s| s.to_string())),
        };
        match &self.variables_setting {
            None => settings.insert("variables_setting".to_string(),
                                    EN.variables_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("variables_setting".to_string(),
                                       self.variables_setting.map(|s| s.to_string())),
        };
        match &self.name_setting {
            None => settings.insert("name_setting".to_string(),
                                    EN.name_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("name_setting".to_string(),
                                       self.name_setting.map(|s| s.to_string()))
        };
        match self.documentation_setting {
            None => settings.insert("documentation_setting".to_string(),
                                    EN.documentation_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("documentation_setting".to_string(),
                                       self.documentation_setting.map(|s| s.to_string())),
        };
        match self.metadata_setting {
            None => settings.insert("metadata_setting".to_string(),
                                    EN.metadata_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("metadata_setting".to_string(),
                                       self.metadata_setting.map(|s| s.to_string())),
        };
        match &self.suite_setup_setting {
            None => settings.insert("suite_setup_setting".to_string(),
                                    EN.suite_setup_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("suite_setup_setting".to_string(),
                                       self.suite_setup_setting.map(|s| s.to_string())),
        };
        match &self.suite_teardown_setting {
            None => settings.insert("suite_teardown_setting".to_string(),
                                    EN.suite_teardown_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("suite_teardown_setting".to_string(),
                                       self.suite_teardown_setting.map(|s| s.to_string())),
        };
        match &self.test_setup_setting {
            None => settings.insert("test_setup_setting".to_string(),
                                    EN.test_setup_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("test_setup_setting".to_string(),
                                       self.test_setup_setting.map(|s| s.to_string())),
        };
        match &self.task_setup_setting {
            None => settings.insert("task_setup_setting".to_string(),
                                    EN.task_setup_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("task_setup_setting".to_string(),
                                       self.task_setup_setting.map(|s| s.to_string())),
        };
        match &self.test_teardown_setting {
            None => settings.insert("test_teardown_setting".to_string(),
                                    EN.test_teardown_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("test_teardown_setting".to_string(),
                                       self.test_teardown_setting.map(|s| s.to_string())),
        };
        match &self.task_teardown_setting {
            None => settings.insert("task_teardown_setting".to_string(),
                                    EN.task_teardown_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("task_teardown_setting".to_string(),
                                       self.task_teardown_setting.map(|s| s.to_string())),
        };
        match &self.test_template_setting {
            None => settings.insert("test_template_setting".to_string(),
                                    EN.test_template_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("test_template_setting".to_string(),
                                       self.test_template_setting.map(|s| s.to_string())),
        };
        match &self.task_template_setting {
            None => settings.insert("task_template_setting".to_string(),
                                    EN.task_template_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("task_template_setting".to_string(),
                                       self.task_template_setting.map(|s| s.to_string())),
        };
        match &self.test_timeout_setting {
            None => settings.insert("test_timeout_setting".to_string(),
                                    EN.test_timeout_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("test_timeout_setting".to_string(),
                                       self.test_timeout_setting.map(|s| s.to_string())),
        };
        match &self.task_timeout_setting {
            None => settings.insert("task_timeout_setting".to_string(),
                                    EN.task_timeout_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("task_timeout_setting".to_string(),
                                       self.task_timeout_setting.map(|s| s.to_string())),
        };
        match &self.test_tags_setting {
            None => settings.insert("test_tags_setting".to_string(),
                                    EN.test_tags_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("test_tags_setting".to_string(),
                                       self.test_tags_setting.map(|s| s.to_string())),
        };
        match &self.task_tags_setting {
            None => settings.insert("task_tags_setting".to_string(),
                                    EN.task_tags_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("task_tags_setting".to_string(),
                                       self.task_tags_setting.map(|s| s.to_string())),
        };
        match &self.keyword_tags_setting {
            None => settings.insert("keyword_tags_setting".to_string(),
                                    EN.keyword_tags_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("keyword_tags_setting".to_string(),
                                       self.keyword_tags_setting.map(|s| s.to_string())),
        };
        match &self.tags_setting {
            None => settings.insert("tags_setting".to_string(),
                                    EN.tags_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("tags_setting".to_string(),
                                       self.tags_setting.map(|s| s.to_string())),
        };
        match &self.setup_setting {
            None => settings.insert("setup_setting".to_string(),
                                    EN.setup_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("setup_setting".to_string(),
                                       self.setup_setting.map(|s| s.to_string())),
        };
        match &self.teardown_setting {
            None => settings.insert("teardown_setting".to_string(),
                                    EN.teardown_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("teardown_setting".to_string(),
                                       self.teardown_setting.map(|s| s.to_string())),
        };
        match &self.template_setting {
            None => settings.insert("template_setting".to_string(),
                                    EN.template_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("template_setting".to_string(),
                                       self.template_setting.map(|s| s.to_string())),
        };
        match &self.timeout_setting {
            None => settings.insert("timeout_setting".to_string(),
                                    EN.timeout_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("timeout_setting".to_string(),
                                       self.timeout_setting.map(|s| s.to_string())),
        };
        match &self.arguments_setting {
            None => settings.insert("arguments_setting".to_string(),
                                    EN.arguments_setting.map(|s| s.to_string())),
            Some(_) => settings.insert("arguments_setting".to_string(),
                                       self.arguments_setting.map(|s| s.to_string())),
        };
        settings
    }

    pub fn get_prefixes(&self) -> HashSet<&'static str> {
        let mut total_set = HashSet::new();
        total_set.extend(self.given_prefixes.iter().cloned());
        total_set.extend(self.when_prefixes.iter().cloned());
        total_set.extend(self.then_prefixes.iter().cloned());
        total_set.extend(self.and_prefixes.iter().cloned());
        total_set.extend(self.but_prefixes.iter().cloned());
        total_set
    }
    fn get_true_strings(&self) -> HashSet<&'static str> {
        let mut total_set = HashSet::new();
        total_set.extend(self.true_strings.iter().cloned());
        total_set
    }

    fn get_false_strings(&self) -> HashSet<&'static str> {
        let mut total_set = HashSet::new();
        total_set.extend(self.true_strings.iter().cloned());
        total_set
    }
}

impl PartialEq for Language {
    fn eq(&self, other: &Self) -> bool {
        self.settings_header.eq(&other.settings_header)
    }
}

pub const EN: Language = Language {
    //English
    settings_header: Some("Settings"),
    variables_header: Some("Variables"),
    test_cases_header: Some("Test Cases"),
    tasks_header: Some("Tasks"),
    keywords_header: Some("Keywords"),
    comments_header: Some("Comments"),
    library_setting: Some("Library"),
    resource_setting: Some("Resource"),
    variables_setting: Some("Variables"),
    name_setting: Some("Name"),
    documentation_setting: Some("Documentation"),
    metadata_setting: Some("Metadata"),
    suite_setup_setting: Some("Suite Setup"),
    suite_teardown_setting: Some("Suite Teardown"),
    test_setup_setting: Some("Test Setup"),
    task_setup_setting: Some("Task Setup"),
    test_teardown_setting: Some("Test Teardown"),
    task_teardown_setting: Some("Task Teardown"),
    test_template_setting: Some("Test Template"),
    task_template_setting: Some("Task Template"),
    test_timeout_setting: Some("Test Timeout"),
    task_timeout_setting: Some("Task Timeout"),
    test_tags_setting: Some("Test Tags"),
    task_tags_setting: Some("Task Tags"),
    keyword_tags_setting: Some("Keyword Tags"),
    setup_setting: Some("Setup"),
    teardown_setting: Some("Teardown"),
    template_setting: Some("Template"),
    tags_setting: Some("Tags"),
    timeout_setting: Some("Timeout"),
    arguments_setting: Some("Arguments"),
    given_prefixes: &["Given"],
    when_prefixes: &["When"],
    then_prefixes: &["Then"],
    and_prefixes: &["And"],
    but_prefixes: &["But"],
    true_strings: &["True", "Yes", "On"],
    false_strings: &["False", "No", "Off"],
};
pub const CS: Language = Language {
    //Czech
    settings_header: Some("Nastavení"),
    variables_header: Some("Proměnné"),
    test_cases_header: Some("Testovací případy"),
    tasks_header: Some("Úlohy"),
    keywords_header: Some("Klíčová slova"),
    comments_header: Some("Komentáře"),
    library_setting: Some("Knihovna"),
    resource_setting: Some("Zdroj"),
    variables_setting: Some("Proměnná"),
    name_setting: Some("Název"),
    documentation_setting: Some("Dokumentace"),
    metadata_setting: Some("Metadata"),
    suite_setup_setting: Some("Příprava sady"),
    suite_teardown_setting: Some("Ukončení sady"),
    test_setup_setting: Some("Příprava testu"),
    test_teardown_setting: Some("Ukončení testu"),
    test_template_setting: Some("Šablona testu"),
    test_timeout_setting: Some("Časový limit testu"),
    test_tags_setting: Some("Štítky testů"),
    task_setup_setting: Some("Příprava úlohy"),
    task_teardown_setting: Some("Ukončení úlohy"),
    task_template_setting: Some("Šablona úlohy"),
    task_timeout_setting: Some("Časový limit úlohy"),
    task_tags_setting: Some("Štítky úloh"),
    keyword_tags_setting: Some("Štítky klíčových slov"),
    tags_setting: Some("Štítky"),
    setup_setting: Some("Příprava"),
    teardown_setting: Some("Ukončení"),
    template_setting: Some("Šablona"),
    timeout_setting: Some("Časový limit"),
    arguments_setting: Some("Argumenty"),
    given_prefixes: &["Pokud"],
    when_prefixes: &["Když"],
    then_prefixes: &["Pak"],
    and_prefixes: &["A"],
    but_prefixes: &["Ale"],
    true_strings: &["Pravda", "Ano", "Zapnuto"],
    false_strings: &["Nepravda", "Ne", "Vypnuto",
        "Nic"],
};
pub const NL: Language = Language {
    //Dutch
    settings_header: Some("Instellingen"),
    variables_header: Some("Variabelen"),
    test_cases_header: Some("Testgevallen"),
    tasks_header: Some("Taken"),
    keywords_header: Some("Sleutelwoorden"),
    comments_header: Some("Opmerkingen"),
    library_setting: Some("Bibliotheek"),
    resource_setting: Some("Resource"),
    variables_setting: Some("Variabele"),
    name_setting: Some("Naam"),
    documentation_setting: Some("Documentatie"),
    metadata_setting: Some("Metadata"),
    suite_setup_setting: Some("Suite Preconditie"),
    suite_teardown_setting: Some("Suite Postconditie"),
    test_setup_setting: Some("Test Preconditie"),
    test_teardown_setting: Some("Test Postconditie"),
    test_template_setting: Some("Test Sjabloon"),
    test_timeout_setting: Some("Test Time-out"),
    test_tags_setting: Some("Test Labels"),
    task_setup_setting: Some("Taak Preconditie"),
    task_teardown_setting: Some("Taak Postconditie"),
    task_template_setting: Some("Taak Sjabloon"),
    task_timeout_setting: Some("Taak Time-out"),
    task_tags_setting: Some("Taak Labels"),
    keyword_tags_setting: Some("Sleutelwoord Labels"),
    tags_setting: Some("Labels"),
    setup_setting: Some("Preconditie"),
    teardown_setting: Some("Postconditie"),
    template_setting: Some("Sjabloon"),
    timeout_setting: Some("Time-out"),
    arguments_setting: Some("Parameters"),
    given_prefixes: &["Stel", "Gegeven"],
    when_prefixes: &["Als"],
    then_prefixes: &["Dan"],
    and_prefixes: &["En"],
    but_prefixes: &["Maar"],
    true_strings: &["Waar", "Ja", "Aan"],
    false_strings: &["Onwaar", "Nee", "Uit",
        "Geen"],
};
pub const BS: Language = Language {
    //Bosnian
    settings_header: Some("Postavke"),
    variables_header: Some("Varijable"),
    test_cases_header: Some("Test Cases"),
    tasks_header: Some("Taskovi"),
    keywords_header: Some("Keywords"),
    comments_header: Some("Komentari"),
    library_setting: Some("Biblioteka"),
    resource_setting: Some("Resursi"),
    variables_setting: Some("Varijable"),
    name_setting: None,
    documentation_setting: Some("Dokumentacija"),
    metadata_setting: Some("Metadata"),
    suite_setup_setting: Some("Suite Postavke"),
    suite_teardown_setting: Some("Suite Teardown"),
    test_setup_setting: Some("Test Postavke"),
    test_teardown_setting: Some("Test Teardown"),
    test_template_setting: Some("Test Template"),
    test_timeout_setting: Some("Test Timeout"),
    test_tags_setting: Some("Test Tagovi"),
    task_setup_setting: Some("Task Postavke"),
    task_teardown_setting: Some("Task Teardown"),
    task_template_setting: Some("Task Template"),
    task_timeout_setting: Some("Task Timeout"),
    task_tags_setting: Some("Task Tagovi"),
    keyword_tags_setting: Some("Keyword Tagovi"),
    tags_setting: Some("Tagovi"),
    setup_setting: Some("Postavke"),
    teardown_setting: Some("Teardown"),
    template_setting: Some("Template"),
    timeout_setting: Some("Timeout"),
    arguments_setting: Some("Argumenti"),
    given_prefixes: &["Uslovno"],
    when_prefixes: &["Kada"],
    then_prefixes: &["Tada"],
    and_prefixes: &["I"],
    but_prefixes: &[],
    true_strings: &[],
    false_strings: &[],
};
pub const FI: Language = Language {
    //Finnish
    settings_header: Some("Asetukset"),
    variables_header: Some("Muuttujat"),
    test_cases_header: Some("Testit"),
    tasks_header: Some("Tehtävät"),
    keywords_header: Some("Avainsanat"),
    comments_header: Some("Kommentit"),
    library_setting: Some("Kirjasto"),
    resource_setting: Some("Resurssi"),
    variables_setting: Some("Muuttujat"),
    documentation_setting: Some("Dokumentaatio"),
    metadata_setting: Some("Metatiedot"),
    name_setting: Some("Nimi"),
    suite_setup_setting: Some("Setin Alustus"),
    suite_teardown_setting: Some("Setin Alasajo"),
    test_setup_setting: Some("Testin Alustus"),
    task_setup_setting: Some("Tehtävän Alustus"),
    test_teardown_setting: Some("Testin Alasajo"),
    task_teardown_setting: Some("Tehtävän Alasajo"),
    test_template_setting: Some("Testin Malli"),
    task_template_setting: Some("Tehtävän Malli"),
    test_timeout_setting: Some("Testin Aikaraja"),
    task_timeout_setting: Some("Tehtävän Aikaraja"),
    test_tags_setting: Some("Testin Tagit"),
    task_tags_setting: Some("Tehtävän Tagit"),
    keyword_tags_setting: Some("Avainsanan Tagit"),
    tags_setting: Some("Tagit"),
    setup_setting: Some("Alustus"),
    teardown_setting: Some("Alasajo"),
    template_setting: Some("Malli"),
    timeout_setting: Some("Aikaraja"),
    arguments_setting: Some("Argumentit"),
    given_prefixes: &["Oletetaan"],
    when_prefixes: &["Kun"],
    then_prefixes: &["Niin"],
    and_prefixes: &["Ja"],
    but_prefixes: &["Mutta"],
    true_strings: &["Tosi", "Kyllä", "Päällä"],
    false_strings: &["Epätosi", "Ei", "Pois"],
};
pub const FR: Language = Language {
    //French
    settings_header: Some("Paramètres"),
    variables_header: Some("Variables"),
    test_cases_header: Some("Unités de test"),
    tasks_header: Some("Tâches"),
    keywords_header: Some("Mots-clés"),
    comments_header: Some("Commentaires"),
    library_setting: Some("Bibliothèque"),
    resource_setting: Some("Ressource"),
    variables_setting: Some("Variable"),
    name_setting: Some("Nom"),
    documentation_setting: Some("Documentation"),
    metadata_setting: Some("Méta-donnée"),
    suite_setup_setting: Some("Mise en place de suite"),
    suite_teardown_setting: Some("Démontage de suite"),
    test_setup_setting: Some("Mise en place de test"),
    test_teardown_setting: Some("Démontage de test"),
    test_template_setting: Some("Modèle de test"),
    test_timeout_setting: Some("Délai de test"),
    test_tags_setting: Some("Étiquette de test"),
    task_setup_setting: Some("Mise en place de tâche"),
    task_teardown_setting: Some("Démontage de test"),
    task_template_setting: Some("Modèle de tâche"),
    task_timeout_setting: Some("Délai de tâche"),
    task_tags_setting: Some("Étiquette de tâche"),
    keyword_tags_setting: Some("Etiquette de mot-clé"),
    tags_setting: Some("Étiquette"),
    setup_setting: Some("Mise en place"),
    teardown_setting: Some("Démontage"),
    template_setting: Some("Modèle"),
    timeout_setting: Some("Délai d'attente"),
    arguments_setting: Some("Arguments"),
    given_prefixes: &["Étant donné"],
    when_prefixes: &["Lorsque"],
    then_prefixes: &["Alors"],
    and_prefixes: &["Et"],
    but_prefixes: &["Mais"],
    true_strings: &["Vrai", "Oui", "Actif"],
    false_strings: &["Faux", "Non", "Désactivé", "Aucun"],
};
pub const DE: Language = Language {
    //German
    settings_header: Some("Einstellungen"),
    variables_header: Some("Variablen"),
    test_cases_header: Some("Testfälle"),
    tasks_header: Some("Aufgaben"),
    keywords_header: Some("Schlüsselwörter"),
    comments_header: Some("Kommentare"),
    library_setting: Some("Bibliothek"),
    resource_setting: Some("Ressource"),
    variables_setting: Some("Variablen"),
    name_setting: Some("Name"),
    documentation_setting: Some("Dokumentation"),
    metadata_setting: Some("Metadaten"),
    suite_setup_setting: Some("Suitevorbereitung"),
    suite_teardown_setting: Some("Suitenachbereitung"),
    test_setup_setting: Some("Testvorbereitung"),
    test_teardown_setting: Some("Testnachbereitung"),
    test_template_setting: Some("Testvorlage"),
    test_timeout_setting: Some("Testzeitlimit"),
    test_tags_setting: Some("Testmarker"),
    task_setup_setting: Some("Aufgabenvorbereitung"),
    task_teardown_setting: Some("Aufgabennachbereitung"),
    task_template_setting: Some("Aufgabenvorlage"),
    task_timeout_setting: Some("Aufgabenzeitlimit"),
    task_tags_setting: Some("Aufgabenmarker"),
    keyword_tags_setting: Some("Schlüsselwortmarker"),
    tags_setting: Some("Marker"),
    setup_setting: Some("Vorbereitung"),
    teardown_setting: Some("Nachbereitung"),
    template_setting: Some("Vorlage"),
    timeout_setting: Some("Zeitlimit"),
    arguments_setting: Some("Argumente"),
    given_prefixes: &["'Angenommen'"],
    when_prefixes: &["Wenn"],
    then_prefixes: &["Dann"],
    and_prefixes: &["Und"],
    but_prefixes: &["Aber"],
    true_strings: &["Wahr", "Ja", "An", "Ein"],
    false_strings: &["Falsch", "Nein", "Aus", "Unwahr"],
};

pub const PT_BR: Language = Language {
    // Brazilian Portuguese
    settings_header: Some("Configurações"),
    variables_header: Some("Variáveis"),
    test_cases_header: Some("Casos de Teste"),
    tasks_header: Some("Tarefas"),
    keywords_header: Some("Palavras-Chave"),
    comments_header: Some("Comentários"),
    library_setting: Some("Biblioteca"),
    resource_setting: Some("Recurso"),
    variables_setting: Some("Variável"),
    name_setting: Some("Nome"),
    documentation_setting: Some("Documentação"),
    metadata_setting: Some("Metadados"),
    suite_setup_setting: Some("Configuração da Suíte"),
    suite_teardown_setting: Some("Finalização de Suíte"),
    test_setup_setting: Some("Inicialização de Teste"),
    test_teardown_setting: Some("Finalização de Teste"),
    test_template_setting: Some("Modelo de Teste"),
    test_timeout_setting: Some("Tempo Limite de Teste"),
    test_tags_setting: Some("Test Tags"),
    task_setup_setting: Some("Inicialização de Tarefa"),
    task_teardown_setting: Some("Finalização de Tarefa"),
    task_template_setting: Some("Modelo de Tarefa"),
    task_timeout_setting: Some("Tempo Limite de Tarefa"),
    task_tags_setting: Some("Task Tags"),
    keyword_tags_setting: Some("Keyword Tags"),
    tags_setting: Some("Etiquetas"),
    setup_setting: Some("Inicialização"),
    teardown_setting: Some("Finalização"),
    template_setting: Some("Modelo"),
    timeout_setting: Some("Tempo Limite"),
    arguments_setting: Some("Argumentos"),
    given_prefixes: &["Dado"],
    when_prefixes: &["Quanto"],
    then_prefixes: &["Então"],
    and_prefixes: &["E"],
    but_prefixes: &["Mas"],
    true_strings: &["Verdadeiro", "Verdade", "Sim", "Ligado"],
    false_strings: &["Falso", "Não", "Desligado", "Desativado", "Nada"],
};
pub const PT: Language = Language {
    //Portuguese
    settings_header: Some("Definições"),
    variables_header: Some("Variáveis"),
    test_cases_header: Some("Casos de Teste"),
    tasks_header: Some("Tarefas"),
    keywords_header: Some("Palavras-Chave"),
    comments_header: Some("Comentários"),
    library_setting: Some("Biblioteca"),
    resource_setting: Some("Recurso"),
    variables_setting: Some("Variável"),
    name_setting: Some("Nome"),
    documentation_setting: Some("Documentação"),
    metadata_setting: Some("Metadados"),
    suite_setup_setting: Some("Inicialização de Suíte"),
    suite_teardown_setting: Some("Finalização de Suíte"),
    test_setup_setting: Some("Inicialização de Teste"),
    test_teardown_setting: Some("Finalização de Teste"),
    test_template_setting: Some("Modelo de Teste"),
    test_timeout_setting: Some("Tempo Limite de Teste"),
    test_tags_setting: Some("Etiquetas de Testes"),
    task_setup_setting: Some("Inicialização de Tarefa"),
    task_teardown_setting: Some("Finalização de Tarefa"),
    task_template_setting: Some("Modelo de Tarefa"),
    task_timeout_setting: Some("Tempo Limite de Tarefa"),
    task_tags_setting: Some("Etiquetas de Tarefas"),
    keyword_tags_setting: Some("Etiquetas de Palavras-Chave"),
    tags_setting: Some("Etiquetas"),
    setup_setting: Some("Inicialização"),
    teardown_setting: Some("Finalização"),
    template_setting: Some("Modelo"),
    timeout_setting: Some("Tempo Limite"),
    arguments_setting: Some("Argumentos"),
    given_prefixes: &["Dado"],
    when_prefixes: &["Quando"],
    then_prefixes: &["Então"],
    and_prefixes: &["E"],
    but_prefixes: &["Mas"],
    true_strings: &["Verdadeiro", "Verdade", "Sim", "Ligado"],
    false_strings: &["Falso", "Não", "Desligado", "Desativado", "Nada"],
};
pub const TH: Language = Language {
    //Thai
    settings_header: Some("การตั้งค่า"),
    variables_header: Some("กำหนดตัวแปร"),
    test_cases_header: Some("การทดสอบ"),
    tasks_header: Some("งาน"),
    keywords_header: Some("คำสั่งเพิ่มเติม"),
    comments_header: Some("คำอธิบาย"),
    library_setting: Some("ชุดคำสั่งที่ใช้"),
    resource_setting: Some("ไฟล์ที่ใช้"),
    variables_setting: Some("ชุดตัวแปร"),
    name_setting: None,
    documentation_setting: Some("เอกสาร"),
    metadata_setting: Some("รายละเอียดเพิ่มเติม"),
    suite_setup_setting: Some("กำหนดค่าเริ่มต้นของชุดการทดสอบ"),
    suite_teardown_setting: Some("คืนค่าของชุดการทดสอบ"),
    test_setup_setting: Some("กำหนดค่าเริ่มต้นของการทดสอบ"),
    task_setup_setting: Some("กำหนดค่าเริ่มต้นของงาน"),
    test_teardown_setting: Some("คืนค่าของการทดสอบ"),
    task_teardown_setting: Some("คืนค่าของงาน"),
    test_template_setting: Some("โครงสร้างของการทดสอบ"),
    task_template_setting: Some("โครงสร้างของงาน"),
    test_timeout_setting: Some("เวลารอของการทดสอบ"),
    task_timeout_setting: Some("เวลารอของงาน"),
    test_tags_setting: Some("กลุ่มของการทดสอบ"),
    task_tags_setting: Some("กลุ่มของงาน"),
    keyword_tags_setting: Some("กลุ่มของคำสั่งเพิ่มเติม"),
    setup_setting: Some("กำหนดค่าเริ่มต้น"),
    teardown_setting: Some("คืนค่า"),
    template_setting: Some("โครงสร้าง"),
    tags_setting: Some("กลุ่ม"),
    timeout_setting: Some("หมดเวลา"),
    arguments_setting: Some("ค่าที่ส่งเข้ามา"),
    given_prefixes: &["กำหนดให้"],
    when_prefixes: &["เมื่อ"],
    then_prefixes: &["ดังนั้น"],
    and_prefixes: &["และ"],
    but_prefixes: &["แต่"],
    true_strings: &[],
    false_strings: &[],
};
pub const PL: Language = Language {
    //Polish
    settings_header: Some("Ustawienia"),
    variables_header: Some("Zmienne"),
    test_cases_header: Some("Przypadki Testowe"),
    tasks_header: Some("Zadania"),
    keywords_header: Some("Słowa Kluczowe"),
    comments_header: Some("Komentarze"),
    library_setting: Some("Biblioteka"),
    resource_setting: Some("Zasób"),
    variables_setting: Some("Zmienne"),
    name_setting: Some("Nazwa"),
    documentation_setting: Some("Dokumentacja"),
    metadata_setting: Some("Metadane"),
    suite_setup_setting: Some("Inicjalizacja Zestawu"),
    suite_teardown_setting: Some("Ukończenie Zestawu"),
    test_setup_setting: Some("Inicjalizacja Testu"),
    test_teardown_setting: Some("Ukończenie Testu"),
    test_template_setting: Some("Szablon Testu"),
    test_timeout_setting: Some("Limit Czasowy Testu"),
    test_tags_setting: Some("Znaczniki Testu"),
    task_setup_setting: Some("Inicjalizacja Zadania"),
    task_teardown_setting: Some("Ukończenie Zadania"),
    task_template_setting: Some("Szablon Zadania"),
    task_timeout_setting: Some("Limit Czasowy Zadania"),
    task_tags_setting: Some("Znaczniki Zadania"),
    keyword_tags_setting: Some("Znaczniki Słowa Kluczowego"),
    tags_setting: Some("Znaczniki"),
    setup_setting: Some("Inicjalizacja"),
    teardown_setting: Some("Ukończenie"),
    template_setting: Some("Szablon"),
    timeout_setting: Some("Limit Czasowy"),
    arguments_setting: Some("Argumenty"),
    given_prefixes: &["Zakładając", "Zakładając, że",
        "Mając"],
    when_prefixes: &["Jeżeli", "Jeśli", "Gdy",
        "Kiedy"],
    then_prefixes: &["Wtedy"],
    and_prefixes: &["Oraz", "I"],
    but_prefixes: &["Ale"],
    true_strings: &["Prawda", "Tak", "Włączone"],
    false_strings: &["Fałsz", "Nie", "Wyłączone"],
};
pub const UK: Language = Language {
    //Ukrainian
    settings_header: Some("Налаштування"),
    variables_header: Some("Змінні"),
    test_cases_header: Some("Тест-кейси"),
    tasks_header: Some("Завдань"),
    keywords_header: Some("Ключових слова"),
    comments_header: Some("Коментарів"),
    library_setting: Some("Бібліотека"),
    resource_setting: Some("Ресурс"),
    variables_setting: Some("Змінна"),
    name_setting: None,
    documentation_setting: Some("Документація"),
    metadata_setting: Some("Метадані"),
    suite_setup_setting: Some("Налаштування Suite"),
    suite_teardown_setting: Some("Розбірка Suite"),
    test_setup_setting: Some("Налаштування тесту"),
    test_teardown_setting: Some("Розбирання тестy"),
    test_template_setting: Some("Тестовий шаблон"),
    test_timeout_setting: Some("Час тестування"),
    test_tags_setting: Some("Тестові теги"),
    task_setup_setting: Some("Налаштування завдання"),
    task_teardown_setting: Some("Розбір завдання"),
    task_template_setting: Some("Шаблон завдання"),
    task_timeout_setting: Some("Час очікування завдання"),
    task_tags_setting: Some("Теги завдань"),
    keyword_tags_setting: Some("Теги ключових слів"),
    tags_setting: Some("Теги"),
    setup_setting: Some("Встановлення"),
    teardown_setting: Some("Cпростовувати пункт за пунктом"),
    template_setting: Some("Шаблон"),
    timeout_setting: Some("Час вийшов"),
    arguments_setting: Some("Аргументи"),
    given_prefixes: &["Дано"],
    when_prefixes: &["Коли"],
    then_prefixes: &["Тоді"],
    and_prefixes: &["Та"],
    but_prefixes: &["Але"],
    true_strings: &[],
    false_strings: &[],
};
pub const ES: Language = Language {
    //Spanish
    settings_header: Some("Configuraciones"),
    variables_header: Some("Variables"),
    test_cases_header: Some("Casos de prueba"),
    tasks_header: Some("Tareas"),
    keywords_header: Some("Palabras clave"),
    comments_header: Some("Comentarios"),
    library_setting: Some("Biblioteca"),
    resource_setting: Some("Recursos"),
    variables_setting: Some("Variable"),
    name_setting: Some("Nombre"),
    documentation_setting: Some("Documentación"),
    metadata_setting: Some("Metadatos"),
    suite_setup_setting: Some("Configuración de la Suite"),
    suite_teardown_setting: Some("Desmontaje de la Suite"),
    test_setup_setting: Some("Configuración de prueba"),
    test_teardown_setting: Some("Desmontaje de la prueba"),
    test_template_setting: Some("Plantilla de prueba"),
    test_timeout_setting: Some("Tiempo de espera de la prueba"),
    test_tags_setting: Some("Etiquetas de la prueba"),
    task_setup_setting: Some("Configuración de tarea"),
    task_teardown_setting: Some("Desmontaje de tareas"),
    task_template_setting: Some("Plantilla de tareas"),
    task_timeout_setting: Some("Tiempo de espera de las tareas"),
    task_tags_setting: Some("Etiquetas de las tareas"),
    keyword_tags_setting: Some("Etiquetas de palabras clave"),
    tags_setting: Some("Etiquetas"),
    setup_setting: Some("Configuración"),
    teardown_setting: Some("Desmontaje"),
    template_setting: Some("Plantilla"),
    timeout_setting: Some("Tiempo agotado"),
    arguments_setting: Some("Argumentos"),
    given_prefixes: &["Dado"],
    when_prefixes: &["Cuando"],
    then_prefixes: &["Entonces"],
    and_prefixes: &["Y"],
    but_prefixes: &["Pero"],
    true_strings: &["Verdadero", "Si", "On"],
    false_strings: &["Falso", "No", "Off",
        "Ninguno"],
};
pub const RU: Language = Language {
    //Russian
    settings_header: Some("Настройки"),
    variables_header: Some("Переменные"),
    test_cases_header: Some("Заголовки тестов"),
    tasks_header: Some("Задача"),
    keywords_header: Some("Ключевые слова"),
    comments_header: Some("Комментарии"),
    library_setting: Some("Библиотека"),
    resource_setting: Some("Ресурс"),
    variables_setting: Some("Переменные"),
    name_setting: None,
    documentation_setting: Some("Документация"),
    metadata_setting: Some("Метаданные"),
    suite_setup_setting: Some("Инициализация комплекта тестов"),
    suite_teardown_setting: Some("Завершение комплекта тестов"),
    test_setup_setting: Some("Инициализация теста"),
    test_teardown_setting: Some("Завершение теста"),
    test_template_setting: Some("Шаблон теста"),
    test_timeout_setting: Some("Лимит выполнения теста"),
    test_tags_setting: Some("Теги тестов"),
    task_setup_setting: Some("Инициализация задания"),
    task_teardown_setting: Some("Завершение задания"),
    task_template_setting: Some("Шаблон задания"),
    task_timeout_setting: Some("Лимит задания"),
    task_tags_setting: Some("Метки заданий"),
    keyword_tags_setting: Some("Метки ключевых слов"),
    tags_setting: Some("Метки"),
    setup_setting: Some("Инициализация"),
    teardown_setting: Some("Завершение"),
    template_setting: Some("Шаблон"),
    timeout_setting: Some("Лимит"),
    arguments_setting: Some("Аргументы"),
    given_prefixes: &["Дано"],
    when_prefixes: &["Когда"],
    then_prefixes: &["Тогда"],
    and_prefixes: &["И"],
    but_prefixes: &["Но"],
    true_strings: &[],
    false_strings: &[],
};
pub const ZH_CN: Language = Language {
    // Chinese Simplified
    settings_header: Some("设置"),
    variables_header: Some("变量"),
    test_cases_header: Some("用例"),
    tasks_header: Some("任务"),
    keywords_header: Some("关键字"),
    comments_header: Some("备注"),
    library_setting: Some("程序库"),
    resource_setting: Some("资源文件"),
    variables_setting: Some("变量文件"),
    name_setting: None,
    documentation_setting: Some("说明"),
    metadata_setting: Some("元数据"),
    suite_setup_setting: Some("用例集启程"),
    suite_teardown_setting: Some("用例集终程"),
    test_setup_setting: Some("用例启程"),
    test_teardown_setting: Some("用例终程"),
    test_template_setting: Some("用例模板"),
    test_timeout_setting: Some("用例超时"),
    test_tags_setting: Some("用例标签"),
    task_setup_setting: Some("任务启程"),
    task_teardown_setting: Some("任务终程"),
    task_template_setting: Some("任务模板"),
    task_timeout_setting: Some("任务超时"),
    task_tags_setting: Some("任务标签"),
    keyword_tags_setting: Some("关键字标签"),
    tags_setting: Some("标签"),
    setup_setting: Some("启程"),
    teardown_setting: Some("终程"),
    template_setting: Some("模板"),
    timeout_setting: Some("超时"),
    arguments_setting: Some("参数"),
    given_prefixes: &["假定"],
    when_prefixes: &["当"],
    then_prefixes: &["那么"],
    and_prefixes: &["并且"],
    but_prefixes: &["但是"],
    true_strings: &["真", "是", "开"],
    false_strings: &["假", "否", "关", "空"],
};
pub const ZH_TW: Language = Language {
    // Chinese Traditional
    settings_header: Some("設置"),
    variables_header: Some("變量"),
    test_cases_header: Some("案例"),
    tasks_header: Some("任務"),
    keywords_header: Some("關鍵字"),
    comments_header: Some("備註"),
    library_setting: Some("函式庫"),
    resource_setting: Some("資源文件"),
    variables_setting: Some("變量文件"),
    name_setting: None,
    documentation_setting: Some("說明"),
    metadata_setting: Some("元數據"),
    suite_setup_setting: Some("測試套啟程"),
    suite_teardown_setting: Some("測試套終程"),
    test_setup_setting: Some("測試啟程"),
    test_teardown_setting: Some("測試終程"),
    test_template_setting: Some("測試模板"),
    test_timeout_setting: Some("測試逾時"),
    test_tags_setting: Some("測試標籤"),
    task_setup_setting: Some("任務啟程"),
    task_teardown_setting: Some("任務終程"),
    task_template_setting: Some("任務模板"),
    task_timeout_setting: Some("任務逾時"),
    task_tags_setting: Some("任務標籤"),
    keyword_tags_setting: Some("關鍵字標籤"),
    tags_setting: Some("標籤"),
    setup_setting: Some("啟程"),
    teardown_setting: Some("終程"),
    template_setting: Some("模板"),
    timeout_setting: Some("逾時"),
    arguments_setting: Some("参数"),
    given_prefixes: &["假定"],
    when_prefixes: &["當"],
    then_prefixes: &["那麼"],
    and_prefixes: &["並且"],
    but_prefixes: &["但是"],
    true_strings: &["真", "是", "開"],
    false_strings: &["假", "否", "關", "空"],
};
pub const TR: Language = Language {
    //Turkish
    settings_header: Some("Ayarlar"),
    variables_header: Some("Değişkenler"),
    test_cases_header: Some("Test Durumları"),
    tasks_header: Some("Görevler"),
    keywords_header: Some("Anahtar Kelimeler"),
    comments_header: Some("Yorumlar"),
    library_setting: Some("Kütüphane"),
    resource_setting: Some("Kaynak"),
    variables_setting: Some("Değişkenler"),
    name_setting: None,
    documentation_setting: Some("Dokümantasyon"),
    metadata_setting: Some("Üstveri"),
    suite_setup_setting: Some("Takım Kurulumu"),
    suite_teardown_setting: Some("Takım Bitişi"),
    test_setup_setting: Some("Test Kurulumu"),
    task_setup_setting: Some("Görev Kurulumu"),
    test_teardown_setting: Some("Test Bitişi"),
    task_teardown_setting: Some("Görev Bitişi"),
    test_template_setting: Some("Test Taslağı"),
    task_template_setting: Some("Görev Taslağı"),
    test_timeout_setting: Some("Test Zaman Aşımı"),
    task_timeout_setting: Some("Görev Zaman Aşımı"),
    test_tags_setting: Some("Test Etiketleri"),
    task_tags_setting: Some("Görev Etiketleri"),
    keyword_tags_setting: Some("Anahtar Kelime Etiketleri"),
    setup_setting: Some("Kurulum"),
    teardown_setting: Some("Bitiş"),
    template_setting: Some("Taslak"),
    tags_setting: Some("Etiketler"),
    timeout_setting: Some("Zaman Aşımı"),
    arguments_setting: Some("Argümanlar"),
    given_prefixes: &["Diyelim ki"],
    when_prefixes: &["Eğer ki"],
    then_prefixes: &["O zaman"],
    and_prefixes: &["Ve"],
    but_prefixes: &["Ancak"],
    true_strings: &["Doğru", "Evet", "Açik"],
    false_strings: &["Yanliş", "Hayir", "Kapali"],
};
pub const SV: Language = Language {
    //Swedish
    settings_header: Some("Inställningar"),
    variables_header: Some("Variabler"),
    test_cases_header: Some("Testfall"),
    tasks_header: Some("Taskar"),
    keywords_header: Some("Nyckelord"),
    comments_header: Some("Kommentarer"),
    library_setting: Some("Bibliotek"),
    resource_setting: Some("Resurs"),
    variables_setting: Some("Variabel"),
    name_setting: Some("Namn"),
    documentation_setting: Some("Dokumentation"),
    metadata_setting: Some("Metadata"),
    suite_setup_setting: Some("Svit konfigurering"),
    suite_teardown_setting: Some("Svit nedrivning"),
    test_setup_setting: Some("Test konfigurering"),
    test_teardown_setting: Some("Test nedrivning"),
    test_template_setting: Some("Test mall"),
    test_timeout_setting: Some("Test timeout"),
    test_tags_setting: Some("Test taggar"),
    task_setup_setting: Some("Task konfigurering"),
    task_teardown_setting: Some("Task nedrivning"),
    task_template_setting: Some("Task mall"),
    task_timeout_setting: Some("Task timeout"),
    task_tags_setting: Some("Arbetsuppgift taggar"),
    keyword_tags_setting: Some("Nyckelord taggar"),
    tags_setting: Some("Taggar"),
    setup_setting: Some("Konfigurering"),
    teardown_setting: Some("Nedrivning"),
    template_setting: Some("Mall"),
    timeout_setting: Some("Timeout"),
    arguments_setting: Some("Argument"),
    given_prefixes: &["Givet"],
    when_prefixes: &["När"],
    then_prefixes: &["Då"],
    and_prefixes: &["Och"],
    but_prefixes: &["Men"],
    true_strings: &["Sant", "Ja", "På"],
    false_strings: &["Falskt", "Nej", "Av", "Ingen"],
};
pub const BG: Language = Language {
    //Bulgarian
    settings_header: Some("Настройки"),
    variables_header: Some("Променливи"),
    test_cases_header: Some("Тестови случаи"),
    tasks_header: Some("Задачи"),
    keywords_header: Some("Ключови думи"),
    comments_header: Some("Коментари"),
    library_setting: Some("Библиотека"),
    resource_setting: Some("Ресурс"),
    variables_setting: Some("Променлива"),
    name_setting: None,
    documentation_setting: Some("Документация"),
    metadata_setting: Some("Метаданни"),
    suite_setup_setting: Some("Първоначални настройки на комплекта"),
    suite_teardown_setting: Some("Приключване на комплекта"),
    test_setup_setting: Some("Първоначални настройки на тестове"),
    test_teardown_setting: Some("Приключване на тестове"),
    test_template_setting: Some("Шаблон за тестове"),
    test_timeout_setting: Some("Таймаут за тестове"),
    test_tags_setting: Some("Етикети за тестове"),
    task_setup_setting: Some("Първоначални настройки на задачи"),
    task_teardown_setting: Some("Приключване на задачи"),
    task_template_setting: Some("Шаблон за задачи"),
    task_timeout_setting: Some("Таймаут за задачи"),
    task_tags_setting: Some("Етикети за задачи"),
    keyword_tags_setting: Some("Етикети за ключови думи"),
    tags_setting: Some("Етикети"),
    setup_setting: Some("Първоначални настройки"),
    teardown_setting: Some("Приключване"),
    template_setting: Some("Шаблон"),
    timeout_setting: Some("Таймаут"),
    arguments_setting: Some("Аргументи"),
    given_prefixes: &["В случай че"],
    when_prefixes: &["Когато"],
    then_prefixes: &["Тогава"],
    and_prefixes: &["И"],
    but_prefixes: &["Но"],
    true_strings: &["Вярно", "Да", "Включен"],
    false_strings: &["Невярно", "Не", "Изключен",
        "Нищо"],
};
pub const RO: Language = Language {
    //Romanian
    settings_header: Some("Setari"),
    variables_header: Some("Variabile"),
    test_cases_header: Some("Cazuri De Test"),
    tasks_header: Some("Sarcini"),
    keywords_header: Some("Cuvinte Cheie"),
    comments_header: Some("Comentarii"),
    library_setting: Some("Librarie"),
    resource_setting: Some("Resursa"),
    variables_setting: Some("Variabila"),
    name_setting: Some("Nume"),
    documentation_setting: Some("Documentatie"),
    metadata_setting: Some("Metadate"),
    suite_setup_setting: Some("Configurare De Suita"),
    suite_teardown_setting: Some("Configurare De Intrerupere"),
    test_setup_setting: Some("Setare De Test"),
    test_teardown_setting: Some("Inrerupere De Test"),
    test_template_setting: Some("Sablon De Test"),
    test_timeout_setting: Some("Timp Expirare Test"),
    test_tags_setting: Some("Taguri De Test"),
    task_setup_setting: Some("Configuarare activitate"),
    task_teardown_setting: Some("Intrerupere activitate"),
    task_template_setting: Some("Sablon de activitate"),
    task_timeout_setting: Some("Timp de expirare activitate"),
    task_tags_setting: Some("Etichete activitate"),
    keyword_tags_setting: Some("Etichete metode"),
    tags_setting: Some("Etichete"),
    setup_setting: Some("Setare"),
    teardown_setting: Some("Intrerupere"),
    template_setting: Some("Sablon"),
    timeout_setting: Some("Expirare"),
    arguments_setting: Some("Argumente"),
    given_prefixes: &["Fie ca"],
    when_prefixes: &["Cand"],
    then_prefixes: &["Atunci"],
    and_prefixes: &["Si"],
    but_prefixes: &["Dar"],
    true_strings: &["Adevarat", "Da", "Cand"],
    false_strings: &["Fals", "Nu", "Oprit", "Niciun"],
};
pub const IT: Language = Language {
    //Italian
    settings_header: Some("Impostazioni"),
    variables_header: Some("Variabili"),
    test_cases_header: Some("Casi Di Test"),
    tasks_header: Some("Attività"),
    keywords_header: Some("Parole Chiave"),
    comments_header: Some("Commenti"),
    library_setting: Some("Libreria"),
    resource_setting: Some("Risorsa"),
    variables_setting: Some("Variabile"),
    name_setting: Some("Nome"),
    documentation_setting: Some("Documentazione"),
    metadata_setting: Some("Metadati"),
    suite_setup_setting: Some("Configurazione Suite"),
    suite_teardown_setting: Some("Distruzione Suite"),
    test_setup_setting: Some("Configurazione Test"),
    test_teardown_setting: Some("Distruzione Test"),
    test_template_setting: Some("Modello Test"),
    test_timeout_setting: Some("Timeout Test"),
    test_tags_setting: Some("Tag Del Test"),
    task_setup_setting: Some("Configurazione Attività"),
    task_teardown_setting: Some("Distruzione Attività"),
    task_template_setting: Some("Modello Attività"),
    task_timeout_setting: Some("Timeout Attività"),
    task_tags_setting: Some("Tag Attività"),
    keyword_tags_setting: Some("Tag Parola Chiave"),
    tags_setting: Some("Tag"),
    setup_setting: Some("Configurazione"),
    teardown_setting: Some("Distruzione"),
    template_setting: Some("Template"),
    timeout_setting: Some("Timeout"),
    arguments_setting: Some("Parametri"),
    given_prefixes: &["Dato"],
    when_prefixes: &["Quando"],
    then_prefixes: &["Allora"],
    and_prefixes: &["E"],
    but_prefixes: &["Ma"],
    true_strings: &["Vero", "Sì", "On"],
    false_strings: &["Falso", "No", "Off", "Nessuno"],
};
pub const HI: Language = Language {
    //Hindi
    settings_header: Some("स्थापना"),
    variables_header: Some("चर"),
    test_cases_header: Some("नियत कार्य प्रवेशिका"),
    tasks_header: Some("कार्य प्रवेशिका"),
    keywords_header: Some("कुंजीशब्द"),
    comments_header: Some("टिप्पणी"),
    library_setting: Some("कोड़ प्रतिबिंब संग्रह"),
    resource_setting: Some("संसाधन"),
    variables_setting: Some("चर"),
    name_setting: None,
    documentation_setting: Some("प्रलेखन"),
    metadata_setting: Some("अधि-आंकड़ा"),
    suite_setup_setting: Some("जांच की शुरुवात"),
    suite_teardown_setting: Some("परीक्षण कार्य अंत"),
    test_setup_setting: Some("परीक्षण कार्य प्रारंभ"),
    test_teardown_setting: Some("परीक्षण कार्य अंत"),
    test_template_setting: Some("परीक्षण ढांचा"),
    test_timeout_setting: Some("परीक्षण कार्य समय समाप्त"),
    test_tags_setting: Some("जाँचका उपनाम"),
    task_setup_setting: Some("परीक्षण कार्य प्रारंभ"),
    task_teardown_setting: Some("परीक्षण कार्य अंत"),
    task_template_setting: Some("परीक्षण ढांचा"),
    task_timeout_setting: Some("कार्य समयबाह्य"),
    task_tags_setting: Some("कार्यका उपनाम"),
    keyword_tags_setting: Some("कुंजीशब्द का उपनाम"),
    tags_setting: Some("निशान"),
    setup_setting: Some("व्यवस्थापना"),
    teardown_setting: Some("विमोचन"),
    template_setting: Some("साँचा"),
    timeout_setting: Some("समय समाप्त"),
    arguments_setting: Some("प्राचल"),
    given_prefixes: &["दिया हुआ"],
    when_prefixes: &["जब"],
    then_prefixes: &["तब"],
    and_prefixes: &["और"],
    but_prefixes: &["परंतु"],
    true_strings: &["यथार्थ", "निश्चित", "हां", "पर"],
    false_strings: &["गलत", "नहीं", "हालाँकि", "यद्यपि", "नहीं", "हैं"],
};
pub const VI: Language = Language {
    // Vietnamese
    settings_header: Some("Cài Đặt"),
    variables_header: Some("Các biến số"),
    test_cases_header: Some("Các kịch bản kiểm thử"),
    tasks_header: Some("Các nghiệm vụ"),
    keywords_header: Some("Các từ khóa"),
    comments_header: Some("Các chú thích"),
    library_setting: Some("Thư viện"),
    resource_setting: Some("Tài nguyên"),
    variables_setting: Some("Biến số"),
    name_setting: Some("Tên"),
    documentation_setting: Some("Tài liệu hướng dẫn"),
    metadata_setting: Some("Dữ liệu tham chiếu"),
    suite_setup_setting: Some("Tiền thiết lập bộ kịch bản kiểm thử"),
    suite_teardown_setting: Some("Hậu thiết lập bộ kịch bản kiểm thử"),
    test_setup_setting: Some("Tiền thiết lập kịch bản kiểm thử"),
    test_teardown_setting: Some("Hậu thiết lập kịch bản kiểm thử"),
    test_template_setting: Some("Mẫu kịch bản kiểm thử"),
    test_timeout_setting: Some("Thời gian chờ kịch bản kiểm thử"),
    test_tags_setting: Some("Các nhãn kịch bản kiểm thử"),
    task_setup_setting: Some("Tiền thiểt lập nhiệm vụ"),
    task_teardown_setting: Some("Hậu thiết lập nhiệm vụ"),
    task_template_setting: Some("Mẫu nhiễm vụ"),
    task_timeout_setting: Some("Thời gian chờ nhiệm vụ"),
    task_tags_setting: Some("Các nhãn nhiệm vụ"),
    keyword_tags_setting: Some("Các từ khóa nhãn"),
    tags_setting: Some("Các thẻ"),
    setup_setting: Some("Tiền thiết lập"),
    teardown_setting: Some("Hậu thiết lập"),
    template_setting: Some("Mẫu"),
    timeout_setting: Some("Thời gian chờ"),
    arguments_setting: Some("Các đối số"),
    given_prefixes: &["Đã cho"],
    when_prefixes: &["Khi"],
    then_prefixes: &["Thì"],
    and_prefixes: &["Và"],
    but_prefixes: &["Nhưng"],
    true_strings: &["Đúng", "Vâng", "Mở"],
    false_strings: &["Sai", "Không", "Tắt", "Không Có Gì"],
};
pub const JA: Language = Language {
    // Japanese
    settings_header: Some("設定"),
    variables_header: Some("変数"),
    test_cases_header: Some("テスト ケース"),
    tasks_header: Some("タスク"),
    keywords_header: Some("キーワード"),
    comments_header: Some("コメント"),
    library_setting: Some("ライブラリ"),
    resource_setting: Some("リソース"),
    variables_setting: Some("変数"),
    name_setting: Some("名前"),
    documentation_setting: Some("ドキュメント"),
    metadata_setting: Some("メタデータ"),
    suite_setup_setting: Some("スイート セットアップ"),
    suite_teardown_setting: Some("スイート ティアダウン"),
    test_setup_setting: Some("テスト セットアップ"),
    task_setup_setting: Some("タスク セットアップ"),
    test_teardown_setting: Some("テスト ティアダウン"),
    task_teardown_setting: Some("タスク ティアダウン"),
    test_template_setting: Some("テスト テンプレート"),
    task_template_setting: Some("タスク テンプレート"),
    test_timeout_setting: Some("テスト タイムアウト"),
    task_timeout_setting: Some("タスク タイムアウト"),
    test_tags_setting: Some("テスト タグ"),
    task_tags_setting: Some("タスク タグ"),
    keyword_tags_setting: Some("キーワード タグ"),
    setup_setting: Some("セットアップ"),
    teardown_setting: Some("ティアダウン"),
    template_setting: Some("テンプレート"),
    tags_setting: Some("タグ"),
    timeout_setting: Some("タイムアウト"),
    arguments_setting: Some("引数"),
    given_prefixes: &["仮定", "指定", "前提条件"],
    when_prefixes: &["条件", "次の場合", "もし", "実行条件"],
    then_prefixes: &["アクション", "その時", "動作"],
    and_prefixes: &["および", "及び", "かつ", "且つ", "ならびに", "並びに", "そして", "それから"],
    but_prefixes: &["ただし", "但し"],
    true_strings: &["真", "有効", "はい", "オン"],
    false_strings: &["偽", "無効", "いいえ", "オフ"],
};